### ISSUE TITLE
New Subcommand for /gamesbot

### ISSUE THREAD

**Issue by itsjusttriz** [TheTurkeyDev/Discord-Games#19]
i see you have `admin_actions` for users with `Administrator` permission. Mind adding a `list_channels` subcommand too, using same permission? Provides quicker insight than doing `... remove` in each channel just to check availability. :)

(*I also see you have the subcommand hidden from the repo, so it prevented me from using the same layout to create a PR LUL*)

**Comment by TheTurkeyDev** [comment]
No longer needed :)
