### ISSUE TITLE
Contributions

### ISSUE THREAD

**Issue by Taz03** [TheTurkeyDev/Discord-Games#21]
do u expect contributions on this repo or is this just for sharing code u wrote in ur videos?

**Comment by TheTurkeyDev** [comment]
You are welcome to contribute! This isn't the repo the live bot uses though, so I would have to manually merge over anything added. If there's something specific you were interested in doing we can talk more about it

**Comment by Taz03** [comment]
> This isn't the repo the live bot uses though

y is that?

**Comment by TheTurkeyDev** [comment]
There's some additional things, mainly database access, that fell outside the scope of this project, but we're needed for a public bot at the scale everyone wanted.
