### ISSUE TITLE
Can’t Play Games

### ISSUE THREAD

**Issue by samlikesspace** [TheTurkeyDev/Discord-Games#27]
@I can’t play any of the games!
![Uploading IMG_1742.jpeg…]()

**Comment by itsjusttriz** [comment]
@HiMyNameIsBob36 the image in your comment is not loading, are you able to re-add it pls.

**Comment by samlikesspace** [comment]
Hope this works
![IMG_1742](https://github.com/TheTurkeyDev/Discord-Games/assets/166279266/1fd606f4-924e-4c42-b6c1-560b7f1b21cb)

**Comment by itsjusttriz** [comment]
@HiMyNameIsBob36 does the bots own role have this permission? 
![image](https://github.com/TheTurkeyDev/Discord-Games/assets/29345907/e6cc0d4c-bbad-4271-801b-55591f29bce5)
 
 **(This permission needs to be on the role that is automatically created when the bot joins the server, not any other random role that you apply to the bot)**

**Comment by samlikesspace** [comment]
Yes it does have that role!

**Comment by itsjusttriz** [comment]
> Yes it does have that role!

which role has this permission though.

**Comment by samlikesspace** [comment]
![IMG_1748](https://github.com/TheTurkeyDev/Discord-Games/assets/166279266/ae6d5223-a4d2-48f0-9ffd-e47e6fbe87a3)

**Comment by itsjusttriz** [comment]
hmm weird. @TheTurkeyDev will probs be better help than me, at this point.

**Comment by samlikesspace** [comment]
I have just given it the admin permission and that works for some reason, thanks for you help!
