### ISSUE TITLE
Minesweeper just opens a new tab but never updates inside discord.

### ISSUE THREAD

**Issue by Ashi360** [TheTurkeyDev/Discord-Games#4]
https://www.loom.com/share/74aa4b08ffe74d459e8c35cd671eb2e2

**Comment by TheTurkeyDev** [comment]
That's just how it is. Minesweeper is only setup to work with my specific implementation. You would need to tweak things and setup your own backend implementation for this to work in your own server

**Comment by Ashi360** [comment]
Like the website, correct?

**Comment by TheTurkeyDev** [comment]
Yes, the "website" it links to is my own and thus interfaces with my specific bot instance

**Comment by Ashi360** [comment]
Ahh, thanks :)
